### ISSUE TITLE
tmos_image_name default value in the module

### ISSUE THREAD

**Issue by ramachittala** [ibm-garage/infrastructure-scripts#9]
In this example `tmos_image_name`

https://github.com/f5devcentral/ibmcloud_schematics_bigip_multinic_public_images/blob/master/variables.tf#L63 

Better to update the variable to support different versions. 
https://github.com/ibm-garage/infrastructure-scripts/blob/master/examples/F5-BIG-IP/F5-BIG-IP/main.tf#L14 
`tmos_image_name = <versions>`

**Comment by ileneruth** [comment]
Thanks for your comment.  Currently, it uses the default image in the f5devcentral terraform.  I could expose image as a parameter, but I don't want to require users to provide it and if I provide a default, it might get out of sync with the latest in f5devcentral.  Ideas on how to deal with that?

**Comment by ramachittala** [comment]
We got to know there was a bug in the tmos image for 15 version. Once we update the toms into 16 version F5 vpn start working.

**Comment by ileneruth** [comment]
Hi @ramachittala - I've updated the example to expose the tmos_image_name as well parameters for urls for declarative scripts.
